### ISSUE TITLE
Buy UPVC paint

### ISSUE THREAD

**Issue by scttmcvy** [hill-farm-cottage/hfc-bunga-upgrade#2]
Zinsser Allcoat Exterior Matt Black

https://www.decoratingwarehouse.co.uk/zinsser-allcoat-exterior-matt-finish

**Comment by scttmcvy** [comment]
![Screenshot 2018-10-14 at 18.32.23.png](https://images.zenhubusercontent.com/5bc32bad2953e703e98ebe59/6cffa27a-c30c-4934-81c5-e85d31f097e3)

**Comment by clrmcvy** [comment]
Delivered Tuesday 16 Oct
