### ISSUE TITLE
Buy masonry paint

### ISSUE THREAD

**Issue by scttmcvy** [hill-farm-cottage/hfc-bunga-upgrade#3]

**Comment by scttmcvy** [comment]
![Screenshot 2018-10-14 at 18.32.43.png](https://images.zenhubusercontent.com/5bc32bad2953e703e98ebe59/8ed916cf-2295-4e79-bd8e-e50e956d3bc8)

**Comment by clrmcvy** [comment]
![image.png](https://images.zenhubusercontent.com/5bc363f22953e703e98ebf3a/7765e6e4-0e6a-4b7d-97c3-87899aa13041)
